language: generic 

sudo: required

services: 
  - docker

before_install: 
  - docker build -t ptthanh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true ptthanh/react-test npm test -- --coverage

after_success:
  - docker build -t ptthanh/multi-client ./client
  - docker build -t ptthanh/multi-nginx ./nginx
  - docker build -t ptthanh/multi-server ./server
  - docker build -t ptthanh/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push them to docker hub

  - docker push ptthanh/multi-client
  - docker push ptthanh/multi-nginx
  - docker push ptthanh/multi-server
  - docker push ptthanh/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ca-central-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-ca-central-1-058264271224'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    