language: generic 

sudo: required

services: 
  - docker

before_install: 
  - docker build -t ptthanh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true ptthanh/react-test npm test -- --coverage

after_success:
  - docker build -t ptthanh/multi-client ./client
  - docker build -t ptthanh/multi-nginx ./nginx
  - docker build -t ptthanh/multi-server ./server
  - docker build -t ptthanh/multi-worker ./worker

